template_function: BILEXICON.template

javascripts:
  admin:
    - app/views/**/*.jst

  workspace:

    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/jquery-1.7.1.js
    - public/javascripts/vendor/jquery-ui-1.8.15.custom.js

    - public/javascripts/vendor/handlebars.js

    - public/javascripts/application.js

    - public/javascripts/bilexicon/helpers.js
    - public/javascripts/bilexicon/search.js
    - public/javascripts/bilexicon/invitation.js
    - public/javascripts/bilexicon/commands.js
    - public/javascripts/bilexicon/commands/*.js
    - public/javascripts/bilexicon/multibutton.js
    - public/javascripts/bilexicon/wordclass.js
    - public/javascripts/bilexicon/quick-delete.js
