template_function: BILEXICON.template

javascripts:
  admin:
    - app/views/**/*.jst

  workspace:

#    - public/javascripts/vendor/prototype.js
#    - public/javascripts/vendor/effects.js
#    - public/javascripts/vendor/controls.js
#    - public/javascripts/vendor/dragdrop.js

    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/jquery-1.5.js
#    - public/javascripts/vendor/jquery-ui-1.8.11.custom.min.js
#    - public/javascripts/vendor/jquery-ui-1.8.15.custom.min.js
    - public/javascripts/vendor/jquery-ui-1.8.15.custom.js
    - public/javascripts/vendor/jquery-noconflict.js

    - public/javascripts/vendor/handlebars.js

    - public/javascripts/application.js

    - public/javascripts/bilexicon/helpers.js
    - public/javascripts/bilexicon/search.js
    - public/javascripts/bilexicon/invitation.js
    - public/javascripts/bilexicon/commands.js
    - public/javascripts/bilexicon/commands/*.js
    - public/javascripts/bilexicon/multibutton.js
    - public/javascripts/bilexicon/wordclass.js
    - public/javascripts/bilexicon/quick-delete.js
